# Generated by Django 2.2.6 on 2019-10-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.SubCategory'),
        ),
    ]
